export const workbenchItems = [
  "activityBar.background", // background
  "activityBar.border", // border
  "activityBar.dropBackground", // background
  "activityBar.foreground", // foreground
  "activityBar.inactiveForeground", // foreground
  "activityBarBadge.background", // background
  "activityBarBadge.foreground", // foreground
  "editorGroup.border", // border
  "editorGroup.dropBackground", // background
  "editorGroup.emptyBackground", // background
  "editorGroup.focusedEmptyBorder", // border
  "editorGroupHeader.noTabsBackground", // background
  "editorGroupHeader.tabsBackground", // background
  "editorGroupHeader.tabsBorder", // border
  "editorPane.background", // background
  "menubar.selectionBackground", // background
  "menubar.selectionBorder", // border
  "menubar.selectionForeground", // foreground
  "notificationCenter.border", // border
  "notificationCenterHeader.background", // background
  "notificationCenterHeader.foreground", // foreground
  "notificationLink.foreground", // foreground
  "notifications.background", // background
  "notifications.border", // border
  "notifications.foreground", // foreground
  "notificationToast.border", // border
  "panel.background", // background
  "panel.border", // border
  "panel.dropBackground", // background
  "panelInput.border", // border
  "panelTitle.activeBorder", // border
  "panelTitle.activeForeground", // foreground
  "panelTitle.inactiveForeground", // foreground
  "sideBar.background", // background
  "sideBar.border", // border
  "sideBar.dropBackground", // background
  "sideBar.foreground", // foreground
  "sideBarSectionHeader.background", // background
  "sideBarSectionHeader.border", // border
  "sideBarSectionHeader.foreground", // foreground
  "sideBarTitle.foreground", // foreground
  "statusBar.background", // background
  "statusBar.border", // border
  "statusBar.foreground", // foreground
  "statusBar.noFolderBackground", // background
  "statusBar.noFolderBorder", // border
  "statusBar.noFolderForeground", // foreground
  "statusBarItem.activeBackground", // background
  "statusBarItem.hostBackground", // background
  "statusBarItem.hostForeground", // foreground
  "statusBarItem.hoverBackground", // background
  "statusBarItem.prominentBackground", // background
  "statusBarItem.prominentForeground", // foreground
  "statusBarItem.prominentHoverBackground", // background
  "tab.activeBackground", // background
  "tab.activeBorder", // border
  "tab.activeBorderTop", // border
  "tab.activeForeground", // foreground
  "tab.activeModifiedBorder", // border
  "tab.border", // border
  "tab.hoverBackground", // background
  "tab.hoverBorder", // border
  "tab.inactiveBackground", // background
  "tab.inactiveForeground", // foreground
  "tab.inactiveModifiedBorder", // border
  "tab.unfocusedActiveBorder", // border
  "tab.unfocusedActiveBorderTop", // border
  "tab.unfocusedActiveForeground", // foreground
  "tab.unfocusedActiveModifiedBorder", // border
  "tab.unfocusedHoverBackground", // background
  "tab.unfocusedHoverBorder", // border
  "tab.unfocusedInactiveForeground", // foreground
  "tab.unfocusedInactiveModifiedBorder", // border
  "titleBar.activeBackground", // background
  "titleBar.activeForeground", // foreground
  "titleBar.border", // border
  "titleBar.inactiveBackground", // background
  "titleBar.inactiveForeground" // foreground
];

export const foregroundItems = [
  // foreground
  "activityBar.foreground", // foreground
  "activityBar.inactiveForeground", // foreground
  "activityBarBadge.foreground", // foreground
  "menubar.selectionForeground", // foreground
  "notificationCenterHeader.foreground", // foreground
  "notificationLink.foreground", // foreground
  "notifications.foreground", // foreground
  "panelTitle.activeForeground", // foreground
  "panelTitle.inactiveForeground", // foreground
  "sideBar.foreground", // foreground
  "sideBarSectionHeader.foreground", // foreground
  "sideBarTitle.foreground", // foreground
  "statusBar.foreground", // foreground
  "statusBar.noFolderForeground", // foreground
  "statusBarItem.hostForeground", // foreground
  "statusBarItem.prominentForeground", // foreground
  "tab.activeForeground", // foreground
  "tab.inactiveForeground", // foreground
  "tab.unfocusedActiveForeground", // foreground
  "tab.unfocusedInactiveForeground", // foreground
  "titleBar.activeForeground", // foreground
  "titleBar.inactiveForeground" // foreground
];

export const backgroudItems = [
  "activityBar.background", // background
  "activityBar.dropBackground", // background
  "activityBarBadge.background", // background
  "editorGroup.dropBackground", // background
  "editorGroup.emptyBackground", // background
  "editorGroupHeader.noTabsBackground", // background
  "editorGroupHeader.tabsBackground", // background
  "editorPane.background", // background
  "menubar.selectionBackground", // background
  "notificationCenterHeader.background", // background
  "notifications.background", // background
  "panel.background", // background
  "panel.dropBackground", // background
  "sideBar.background", // background
  "sideBar.dropBackground", // background
  "sideBarSectionHeader.background", // background
  "statusBar.background", // background
  "statusBar.noFolderBackground", // background
  "statusBarItem.activeBackground", // background
  "statusBarItem.hostBackground", // background
  "statusBarItem.hoverBackground", // background
  "statusBarItem.prominentBackground", // background
  "statusBarItem.prominentHoverBackground", // background
  "tab.activeBackground", // background
  "tab.hoverBackground", // background
  "tab.inactiveBackground", // background
  "tab.unfocusedHoverBackground", // background
  "titleBar.activeBackground", // background
  "titleBar.inactiveBackground" // background
];

export const borderItems = [
  "activityBar.border", // border
  "editorGroup.border", // border
  "editorGroup.focusedEmptyBorder", // border
  "editorGroupHeader.tabsBorder", // border
  "menubar.selectionBorder", // border
  "notificationCenter.border", // border
  "notifications.border", // border
  "notificationToast.border", // border
  "panel.border", // border
  "panelInput.border", // border
  "panelTitle.activeBorder", // border
  "sideBar.border", // border
  "sideBarSectionHeader.border", // border
  "statusBar.border", // border
  "statusBar.noFolderBorder", // border
  "tab.activeBorder", // border
  "tab.activeBorderTop", // border
  "tab.activeModifiedBorder", // border
  "tab.border", // border
  "tab.hoverBorder", // border
  "tab.inactiveModifiedBorder", // border
  "tab.unfocusedActiveBorder", // border
  "tab.unfocusedActiveBorderTop", // border
  "tab.unfocusedActiveModifiedBorder", // border
  "tab.unfocusedHoverBorder", // border
  "tab.unfocusedInactiveModifiedBorder", // border
  "titleBar.border" // border
];
