const array1 = [
  "constant.language.access-type.jsdoc",
  "constant.language.symbol-type.jsdoc",
  "constant.other.description.jsdoc",
  "constant.other.description.jsdoc",
  "constant.other.email.link.underline.jsdoc",
  "constant.other.email.link.underline.jsdoc",
  "entity.name.tag.inline.jsdoc",
  "entity.name.tag.inline.jsdoc",
  "entity.name.type.instance.jsdoc",
  "entity.name.type.instance.jsdoc",
  "keyword.operator.assignment.jsdoc",
  "keyword.operator.assignment.jsdoc",
  "keyword.operator.control.jsdoc",
  "keyword.operator.control.jsdoc",
  "meta.example.jsdoc",
  "punctuation.definition.bracket.angle.begin.jsdoc",
  "punctuation.definition.bracket.angle.begin.jsdoc",
  "punctuation.definition.bracket.angle.end.jsdoc",
  "punctuation.definition.bracket.angle.end.jsdoc",
  "punctuation.definition.bracket.curly.begin.jsdoc",
  "punctuation.definition.bracket.curly.begin.jsdoc",
  "punctuation.definition.bracket.curly.end.jsdoc",
  "punctuation.definition.bracket.curly.end.jsdoc",
  "punctuation.definition.bracket.square.begin.jsdoc",
  "punctuation.definition.bracket.square.begin.jsdoc",
  "punctuation.definition.bracket.square.end.jsdoc",
  "punctuation.definition.bracket.square.end.jsdoc",
  "punctuation.definition.inline.tag.jsdoc",
  "punctuation.definition.inline.tag.jsdoc",
  "punctuation.definition.optional-value.begin.bracket.square.jsdoc",
  "punctuation.definition.optional-value.begin.bracket.square.jsdoc",
  "punctuation.definition.optional-value.end.bracket.square.jsdoc",
  "punctuation.definition.optional-value.end.bracket.square.jsdoc",
  "punctuation.definition.string.begin.jsdoc",
  "punctuation.definition.string.begin.jsdoc",
  "punctuation.definition.string.end.jsdoc",
  "punctuation.definition.string.end.jsdoc",
  "punctuation.separator.pipe.jsdoc",
  "punctuation.separator.pipe.jsdoc",
  "storage.type.class.jsdoc punctuation.definition.block.tag.jsdoc",
  "storage.type.class.jsdoc",
  "variable.other.description.jsdoc",
  "variable.other.description.jsdoc",
  "variable.other.jsdoc",
  "variable.other.jsdoc",
  "variable.other.link.underline.jsdoc",
  "variable.other.link.underline.jsdoc"
];

const array2 = [...new Set(array1)];
array2.forEach(value => console.log('"' + value + '" ,'));
