const oneArray: string[] = [
  "foreground",
  "errorForeground",
  "descriptionForeground",
  "focusBorder",
  "contrastBorder",
  "contrastActiveBorder",
  "selection.background",
  "textSeparator.foreground",
  "textLink.foreground",
  "textLink.activeForeground",
  "textPreformat.foreground",
  "textBlockQuote.background",
  "textBlockQuote.border",
  "textCodeBlock.background",
  "widget.shadow",
  "input.background",
  "input.foreground",
  "input.border",
  "inputOption.activeBorder",
  "input.placeholderForeground",
  "inputValidation.infoBackground",
  "inputValidation.infoForeground",
  "inputValidation.infoBorder",
  "inputValidation.warningBackground",
  "inputValidation.warningForeground",
  "inputValidation.warningBorder",
  "inputValidation.errorBackground",
  "inputValidation.errorForeground",
  "inputValidation.errorBorder",
  "dropdown.background",
  "dropdown.listBackground",
  "dropdown.foreground",
  "dropdown.border",
  "list.focusBackground",
  "list.focusForeground",
  "list.activeSelectionBackground",
  "list.activeSelectionForeground",
  "list.inactiveSelectionBackground",
  "list.inactiveSelectionForeground",
  "list.inactiveFocusBackground",
  "list.hoverBackground",
  "list.hoverForeground",
  "list.dropBackground",
  "list.highlightForeground",
  "list.invalidItemForeground",
  "list.errorForeground",
  "list.warningForeground",
  "listFilterWidget.background",
  "listFilterWidget.outline",
  "listFilterWidget.noMatchesOutline",
  "pickerGroup.foreground",
  "pickerGroup.border",
  "button.foreground",
  "button.background",
  "button.hoverBackground",
  "badge.background",
  "badge.foreground",
  "scrollbar.shadow",
  "scrollbarSlider.background",
  "scrollbarSlider.hoverBackground",
  "scrollbarSlider.activeBackground",
  "progressBar.background",
  "menu.border",
  "menu.foreground",
  "menu.background",
  "menu.selectionForeground",
  "menu.selectionBackground",
  "menu.selectionBorder",
  "menu.separatorBackground",
  "editor.background",
  "editor.foreground",
  "editorWidget.background",
  "editorWidget.border",
  "editorWidget.resizeBorder",
  "editor.selectionBackground",
  "editor.selectionForeground",
  "editor.inactiveSelectionBackground",
  "editor.selectionHighlightBackground",
  "editor.selectionHighlightBorder",
  "editor.findMatchBackground",
  "editor.findMatchHighlightBackground",
  "editor.findRangeHighlightBackground",
  "editor.findMatchBorder",
  "editor.findMatchHighlightBorder",
  "editor.findRangeHighlightBorder",
  "editor.hoverHighlightBackground",
  "editorHoverWidget.background",
  "editorHoverWidget.border",
  "editorHoverWidget.statusBarBackground",
  "editorLink.activeForeground",
  "diffEditor.insertedTextBackground",
  "diffEditor.removedTextBackground",
  "diffEditor.insertedTextBorder",
  "diffEditor.removedTextBorder",
  "diffEditor.border",
  "editor.snippetTabstopHighlightBackground",
  "editor.snippetTabstopHighlightBorder",
  "editor.snippetFinalTabstopHighlightBackround'",
  "editor.snippetFinalTabstopHighlightBorder",
  "breadcrumb.foreground",
  "breadcrumb.background",
  "breadcrumb.focusForeground",
  "breadcrumb.activeSelectionForeground",
  "breadcrumbPicker.background",
  "merge.currentHeaderBackground",
  "merge.currentContentBackground",
  "merge.incomingHeaderBackground",
  "merge.incomingContentBackground",
  "merge.commonHeaderBackground",
  "merge.commonContentBackground",
  "merge.border",
  "editorOverviewRuler.currentContentForeground",
  "editorOverviewRuler.incomingContentForeground",
  "editorOverviewRuler.commonContentForeground",
  "editorOverviewRuler.findMatchForeground",
  "editorOverviewRuler.selectionHighlightForeground",
  "foreground",
  "errorForeground",
  "descriptionForeground",
  "focusBorder",
  "contrastBorder",
  "contrastActiveBorder",
  "selection.background",
  "textSeparator.foreground",
  "textLink.foreground",
  "textLink.activeForeground",
  "textPreformat.foreground",
  "textBlockQuote.background",
  "textBlockQuote.border",
  "textCodeBlock.background",
  "widget.shadow",
  "input.background",
  "input.foreground",
  "input.border",
  "inputOption.activeBorder",
  "input.placeholderForeground",
  "inputValidation.infoBackground",
  "inputValidation.infoForeground",
  "inputValidation.infoBorder",
  "inputValidation.warningBackground",
  "inputValidation.warningForeground",
  "inputValidation.warningBorder",
  "inputValidation.errorBackground",
  "inputValidation.errorForeground",
  "inputValidation.errorBorder",
  "dropdown.background",
  "dropdown.listBackground",
  "dropdown.foreground",
  "dropdown.border",
  "list.focusBackground",
  "list.focusForeground",
  "list.activeSelectionBackground",
  "list.activeSelectionForeground",
  "list.inactiveSelectionBackground",
  "list.inactiveSelectionForeground",
  "list.inactiveFocusBackground",
  "list.hoverBackground",
  "list.hoverForeground",
  "list.dropBackground",
  "list.highlightForeground",
  "list.invalidItemForeground",
  "list.errorForeground",
  "list.warningForeground",
  "listFilterWidget.background",
  "listFilterWidget.outline",
  "listFilterWidget.noMatchesOutline",
  "pickerGroup.foreground",
  "pickerGroup.border",
  "button.foreground",
  "button.background",
  "button.hoverBackground",
  "badge.background",
  "badge.foreground",
  "scrollbar.shadow",
  "scrollbarSlider.background",
  "scrollbarSlider.hoverBackground",
  "scrollbarSlider.activeBackground",
  "progressBar.background",
  "menu.border",
  "menu.foreground",
  "menu.background",
  "menu.selectionForeground",
  "menu.selectionBackground",
  "menu.selectionBorder",
  "menu.separatorBackground",
  "editor.background",
  "editor.foreground",
  "editorWidget.background",
  "editorWidget.border",
  "editorWidget.resizeBorder",
  "editor.selectionBackground",
  "editor.selectionForeground",
  "editor.inactiveSelectionBackground",
  "editor.selectionHighlightBackground",
  "editor.selectionHighlightBorder",
  "editor.findMatchBackground",
  "editor.findMatchHighlightBackground",
  "editor.findRangeHighlightBackground",
  "editor.findMatchBorder",
  "editor.findMatchHighlightBorder",
  "editor.findRangeHighlightBorder",
  "editor.hoverHighlightBackground",
  "editorHoverWidget.background",
  "editorHoverWidget.border",
  "editorHoverWidget.statusBarBackground",
  "editorLink.activeForeground",
  "diffEditor.insertedTextBackground",
  "diffEditor.removedTextBackground",
  "diffEditor.insertedTextBorder",
  "diffEditor.removedTextBorder",
  "diffEditor.border",
  "editor.snippetTabstopHighlightBackground",
  "editor.snippetTabstopHighlightBorder",
  "editor.snippetFinalTabstopHighlightBackround'",
  "editor.snippetFinalTabstopHighlightBorder",
  "breadcrumb.foreground",
  "breadcrumb.background",
  "breadcrumb.focusForeground",
  "breadcrumb.activeSelectionForeground",
  "breadcrumbPicker.background",
  "merge.currentHeaderBackground",
  "merge.currentContentBackground",
  "merge.incomingHeaderBackground",
  "merge.incomingContentBackground",
  "merge.commonHeaderBackground",
  "merge.commonContentBackground",
  "merge.border",
  "editorOverviewRuler.currentContentForeground",
  "editorOverviewRuler.incomingContentForeground",
  "editorOverviewRuler.commonContentForeground",
  "editorOverviewRuler.findMatchForeground",
  "editorOverviewRuler.selectionHighlightForeground"
];
const array = [...new Set(oneArray)].forEach(element => {
  console.log(`"${element.toString()}": "",`);
});

/*

"foreground": "",
"errorForeground": "",
"descriptionForeground": "",
"focusBorder": "",
"contrastBorder": "",
"contrastActiveBorder": "",
"selection.background": "",
"textSeparator.foreground": "",
"textLink.foreground": "",
"textLink.activeForeground": "",
"textPreformat.foreground": "",
"textBlockQuote.background": "",
"textBlockQuote.border": "",
"textCodeBlock.background": "",
"widget.shadow": "",
"input.background": "",
"input.foreground": "",
"input.border": "",
"inputOption.activeBorder": "",
"input.placeholderForeground": "",
"inputValidation.infoBackground": "",
"inputValidation.infoForeground": "",
"inputValidation.infoBorder": "",
"inputValidation.warningBackground": "",
"inputValidation.warningForeground": "",
"inputValidation.warningBorder": "",
"inputValidation.errorBackground": "",
"inputValidation.errorForeground": "",
"inputValidation.errorBorder": "",
"dropdown.background": "",
"dropdown.listBackground": "",
"dropdown.foreground": "",
"dropdown.border": "",
"list.focusBackground": "",
"list.focusForeground": "",
"list.activeSelectionBackground": "",
"list.activeSelectionForeground": "",
"list.inactiveSelectionBackground": "",
"list.inactiveSelectionForeground": "",
"list.inactiveFocusBackground": "",
"list.hoverBackground": "",
"list.hoverForeground": "",
"list.dropBackground": "",
"list.highlightForeground": "",
"list.invalidItemForeground": "",
"list.errorForeground": "",
"list.warningForeground": "",
"listFilterWidget.background": "",
"listFilterWidget.outline": "",
"listFilterWidget.noMatchesOutline": "",
"pickerGroup.foreground": "",
"pickerGroup.border": "",
"button.foreground": "",
"button.background": "",
"button.hoverBackground": "",
"badge.background": "",
"badge.foreground": "",
"scrollbar.shadow": "",
"scrollbarSlider.background": "",
"scrollbarSlider.hoverBackground": "",
"scrollbarSlider.activeBackground": "",
"progressBar.background": "",
"menu.border": "",
"menu.foreground": "",
"menu.background": "",
"menu.selectionForeground": "",
"menu.selectionBackground": "",
"menu.selectionBorder": "",
"menu.separatorBackground": "",
"editor.background": "",
"editor.foreground": "",
"editorWidget.background": "",
"editorWidget.border": "",
"editorWidget.resizeBorder": "",
"editor.selectionBackground": "",
"editor.selectionForeground": "",
"editor.inactiveSelectionBackground": "",
"editor.selectionHighlightBackground": "",
"editor.selectionHighlightBorder": "",
"editor.findMatchBackground": "",
"editor.findMatchHighlightBackground": "",
"editor.findRangeHighlightBackground": "",
"editor.findMatchBorder": "",
"editor.findMatchHighlightBorder": "",
"editor.findRangeHighlightBorder": "",
"editor.hoverHighlightBackground": "",
"editorHoverWidget.background": "",
"editorHoverWidget.border": "",
"editorHoverWidget.statusBarBackground": "",
"editorLink.activeForeground": "",
"diffEditor.insertedTextBackground": "",
"diffEditor.removedTextBackground": "",
"diffEditor.insertedTextBorder": "",
"diffEditor.removedTextBorder": "",
"diffEditor.border": "",
"editor.snippetTabstopHighlightBackground": "",
"editor.snippetTabstopHighlightBorder": "",
"editor.snippetFinalTabstopHighlightBackround'": "",
"editor.snippetFinalTabstopHighlightBorder": "",
"breadcrumb.foreground": "",
"breadcrumb.background": "",
"breadcrumb.focusForeground": "",
"breadcrumb.activeSelectionForeground": "",
"breadcrumbPicker.background": "",
"merge.currentHeaderBackground": "",
"merge.currentContentBackground": "",
"merge.incomingHeaderBackground": "",
"merge.incomingContentBackground": "",
"merge.commonHeaderBackground": "",
"merge.commonContentBackground": "",
"merge.border": "",
"editorOverviewRuler.currentContentForeground": "",
"editorOverviewRuler.incomingContentForeground": "",
"editorOverviewRuler.commonContentForeground": "",
"editorOverviewRuler.findMatchForeground": "",
"editorOverviewRuler.selectionHighlightForeground": "",

*/
